version: "2"
services:
  api45_gateway7:
    build: ./back-end/core/bussiness/APIGateway
    command: node app.js apigateapp
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3001:3001"

  layers_busines7:
    build: ./back-end/core/bussiness/LayersBusiness
    command: node app.js layersapp
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3008:3008"

  user_business7:
    build: ./back-end/core/bussiness/UserBusiness
    command: node app.js userpapp
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3002:3002"

  user_persistence7:
    build: ./back-end/core/db/UsersDbService
    command: node app.js userdbapp
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3003:3003"

  nodes_persistence10:
    build: ./back-end/core/db/NodesDbService
    command: node app.js nodedbsapp
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3005:3005"

  layers_persistence7:
    build: ./back-end/core/db/LayersDbService
    command: node app.js layersdbapp
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3007:3007"
