
# syntax=docker/dockerfile:1

FROM tensorflow/tensorflow

WORKDIR /app

COPY requirements.txt requirements.txt
RUN apk update
RUN apk add make automake gcc g++ subversion python3-dev
RUN pip3 install -r requirements.txt

COPY . .

CMD [ "python3", "./new.py"]
